

services:
  auth-db:
    container_name: auth-db
    image: postgres:latest
    environment:
      POSTGRES_USER: auth
      POSTGRES_PASSWORD: password
      POSTGRES_DB: authdb
    ports:
      - "5434:5432"
    volumes:
      - auth-pgdata:/var/lib/postgresql/data

volumes:
  auth-pgdata: {}